# Generated by Django 3.2.25 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241006_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendOutPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=225)),
                ('laptop_name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='owner',
            field=models.CharField(default='EasyLendPC', max_length=225),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(max_length=225),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
