# Generated by Django 3.2.25 on 2024-10-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241008_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=220),
        ),
    ]
