# Generated by Django 3.2.25 on 2024-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lendoutpc_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendoutpc',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='lendoutpc',
            name='pc_description',
            field=models.TextField(max_length=225),
        ),
    ]
