# Generated by Django 3.2.25 on 2024-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241009_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
